name: Generate Profile Assets (snake + 3D)

on:
  schedule:
    - cron: "0 0 * * *"   # daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generate Snake Animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate 3D contribution graph
      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Commit & Push generated assets to 'output' branch
      - name: Commit & Push outputs
        run: |
          set -e

          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Switch to output branch if it exists, otherwise create orphan
          if git rev-parse --verify output; then
            git checkout output
          else
            git checkout --orphan output
            git rm -rf .
          fi

          # Remove old generated assets
          rm -rf dist profile-3d-contrib

          # Ensure folders exist before committing
          mkdir -p dist profile-3d-contrib

          # Copy generated files if they exist
          [ -f dist/snake.svg ] && cp dist/snake.svg dist/
          [ -f dist/snake-dark.svg ] && cp dist/snake-dark.svg dist/
          [ -f profile-3d-contrib/profile-night-rainbow.svg ] && cp profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/

          # Add only existing files
          git add dist profile-3d-contrib || true

          # Exit if nothing changed
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update generated assets (snake + 3D)"
          git push -u origin output --force
