name: Generate Profile Assets (snake + 3D)

on:
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Generate Snake Animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate 3D contribution graph
      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Commit & Push generated assets to 'output' branch
      - name: Commit & Push outputs
        run: |
          set -e

          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Create or switch to 'output' branch safely
          if git ls-remote --exit-code origin output >/dev/null 2>&1; then
            git fetch origin output
            git checkout output
          else
            git checkout --orphan output
            git rm -rf .
          fi

          # Copy generated files from main workspace
          mkdir -p dist profile-3d-contrib

          if [ -f dist/snake.svg ]; then
            echo "✅ Snake generated"
          else
            echo "⚠️ Snake file not found!"
          fi

          if [ -f profile-3d-contrib/profile-night-rainbow.svg ]; then
            echo "✅ 3D graph generated"
          else
            echo "⚠️ 3D graph file not found!"
          fi

          # Add only if files exist
          git add dist profile-3d-contrib || true

          # Commit and push changes if there are any
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update generated assets (snake + 3D)"
          git push -f origin output
