name: Generate Profile Assets (snake + 3D)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # -- Generate Snake Animation --
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # -- Generate 3D graph --
      - name: Generate 3D contribution
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # -- Push generated assets to output branch --
      - name: Commit & Push outputs
        run: |
          set -e

          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Switch to output branch, create if not exists
          if git rev-parse --verify output; then
            git checkout output
          else
            git checkout --orphan output
            git rm -rf .
          fi

          # Clear old generated files
          rm -rf dist profile-3d-contrib

          # Copy newly generated files
          cp -r dist dist
          cp -r profile-3d-contrib profile-3d-contrib || true

          git add dist profile-3d-contrib

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update generated assets (snake + 3D)"
          git push -u origin output --force
