name: GitHub Snake
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run classic snake
        uses: Platane/snk@v0.7.0
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: "./snake.svg"

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "generate snake" || echo "no changes to commit"
          git push || echo "push failed"
